FROM mcr.microsoft.com/devcontainers/cpp:1-ubuntu-22.04

RUN apt-get update && apt-get -y install --no-install-recommends gcc-12 g++-12 gdb cmake python3-pip && python3 -m pip install -U pip && python3 -m pip install -U matplotlib
